[package]
name = "core_profiler"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2"
argh = "0.1.12"
csv = "1.3.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ndarray = "0.15"
libm = "0.2"

[build-dependencies]
cc = "1.0"